/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as LibrariesRouteImport } from './routes/libraries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiPolicyRouteImport } from './routes/ai-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolSlugRouteImport } from './routes/tool.$slug'
import { Route as TagSlugRouteImport } from './routes/tag.$slug'
import { Route as StyleSlugRouteImport } from './routes/style.$slug'
import { Route as PromptSlugRouteImport } from './routes/prompt.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRoute = LibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPolicyRoute = AiPolicyRouteImport.update({
  id: '/ai-policy',
  path: '/ai-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleSlugRoute = StyleSlugRouteImport.update({
  id: '/style/$slug',
  path: '/style/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptSlugRoute = PromptSlugRouteImport.update({
  id: '/prompt/$slug',
  path: '/prompt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-policy': typeof AiPolicyRoute
  '/contact': typeof ContactRoute
  '/libraries': typeof LibrariesRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/style/$slug': typeof StyleSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-policy': typeof AiPolicyRoute
  '/contact': typeof ContactRoute
  '/libraries': typeof LibrariesRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/style/$slug': typeof StyleSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-policy': typeof AiPolicyRoute
  '/contact': typeof ContactRoute
  '/libraries': typeof LibrariesRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prompt/$slug': typeof PromptSlugRoute
  '/style/$slug': typeof StyleSlugRoute
  '/tag/$slug': typeof TagSlugRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-policy'
    | '/contact'
    | '/libraries'
    | '/premium'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/category/$slug'
    | '/prompt/$slug'
    | '/style/$slug'
    | '/tag/$slug'
    | '/tool/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-policy'
    | '/contact'
    | '/libraries'
    | '/premium'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/category/$slug'
    | '/prompt/$slug'
    | '/style/$slug'
    | '/tag/$slug'
    | '/tool/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-policy'
    | '/contact'
    | '/libraries'
    | '/premium'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/category/$slug'
    | '/prompt/$slug'
    | '/style/$slug'
    | '/tag/$slug'
    | '/tool/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiPolicyRoute: typeof AiPolicyRoute
  ContactRoute: typeof ContactRoute
  LibrariesRoute: typeof LibrariesRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PromptSlugRoute: typeof PromptSlugRoute
  StyleSlugRoute: typeof StyleSlugRoute
  TagSlugRoute: typeof TagSlugRoute
  ToolSlugRoute: typeof ToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-policy': {
      id: '/ai-policy'
      path: '/ai-policy'
      fullPath: '/ai-policy'
      preLoaderRoute: typeof AiPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style/$slug': {
      id: '/style/$slug'
      path: '/style/$slug'
      fullPath: '/style/$slug'
      preLoaderRoute: typeof StyleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt/$slug': {
      id: '/prompt/$slug'
      path: '/prompt/$slug'
      fullPath: '/prompt/$slug'
      preLoaderRoute: typeof PromptSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiPolicyRoute: AiPolicyRoute,
  ContactRoute: ContactRoute,
  LibrariesRoute: LibrariesRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  PromptSlugRoute: PromptSlugRoute,
  StyleSlugRoute: StyleSlugRoute,
  TagSlugRoute: TagSlugRoute,
  ToolSlugRoute: ToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
